# Makefile for CSE 13S, Spring 2023, Assignment 3

# DO NOT EDIT THIS FILE

# Usage:
#
#    $ make             Make the program (ready for LLDB debugging).
#    $ make all
#
#    $ make clean       Type this command after editing this Makefile or
#                       when switching between all and release targets.
#
#    $ make format      Run clang-format on *.c and *.h
#
#    $ make release     Make the sorting program (without debugging info).
#                       We use this for the reference design.


CC=clang
CFLAGS=-Wall -Wextra -Wstrict-prototypes -Werror -pedantic -g
LDFLAGS=-lm

EXECBIN_COLORB=colorb
EXECBIN_IOTEST=iotest

OBJS=\
    bmp.o \
    io.o \

.PHONY: all debug release clean colorb iotest

all: debug colorb iotest

debug: $(OBJS)
	$(CC) $(CFLAGS) -o $(EXECBIN_COLORB) colorb.c $(OBJS)
	$(CC) $(CFLAGS) -o $(EXECBIN_IOTEST) iotest.c $(OBJS)

colorb: $(OBJS)
	$(CC) $(CFLAGS) -o $(EXECBIN_COLORB) colorb.c $(OBJS)

iotest: $(OBJS)
	$(CC) $(CFLAGS) -o $(EXECBIN_IOTEST) iotest.c $(OBJS)

bmp.o: bmp.c bmp.h
	$(CC) $(CFLAGS) -c bmp.c

io.o: io.c io.h
	$(CC) $(CFLAGS) -c io.c

clean:
	rm -f $(EXECBIN_COLORB) $(EXECBIN_IOTEST) $(OBJS)

format:
	clang-format -i --style=file *.[ch]
